-- =============================================================================
-- Financial Truth Engine (FTE) — Review Resolutions
-- Migration: 002_add_review_resolutions.sql
-- Depends on: 001_create_financial_truth_schema.sql
-- Created: 2026-06-20
--
-- WHY THIS TABLE EXISTS
-- -----------------------------------------------------------------------------
-- The reconciler (fte_reconcile.sql) is idempotent: Phase 0 deletes all derived
-- rows (fte_event_evidence -> fte_review_queue -> fte_financial_positions ->
-- fte_claim_events) and rebuilds them from scratch on every call. This is
-- correct for financial truth — but it means a human reviewer's decision has no
-- mechanism to survive a reprocess.
--
-- fte_review_resolutions is the solution: an append-only table of typed reviewer
-- decisions that Phase 0 never touches. It carries hard FKs ONLY to stable
-- entity tables whose IDs survive across reprocesses:
--
--   practice_id   -> fte_practices     (tenant root, never deleted)
--   claim_id      -> fte_claims        (entity layer, never deleted by Phase 0)
--   observation_id -> fte_observations (evidence layer, never deleted by Phase 0)
--   evidence_id   -> fte_evidence      (immutable, never deleted)
--
-- VOLATILE DERIVED-ROW IDs
-- -----------------------------------------------------------------------------
-- The IDs of fte_review_queue, fte_claim_events, and fte_financial_positions are
-- NOT stable across reruns — they are generated with gen_random_uuid() at
-- reconciler runtime and discarded by Phase 0 on every call. This migration
-- captures them as SNAPSHOT FIELDS (plain uuid columns, no REFERENCES clause)
-- for audit context only. They become stale after a reprocess — that is expected
-- and acceptable for snapshot purposes.
--
-- If an enforced FK pointed at these tables:
--   ON DELETE CASCADE -> Phase 0 would destroy reviewer history.
--   ON DELETE RESTRICT -> Phase 0's DELETE would fail with a FK violation.
-- Neither outcome is acceptable. Hence: no REFERENCES on volatile snapshot cols.
--
-- PHASE 0.5
-- -----------------------------------------------------------------------------
-- A new sub-phase (Phase 0.5) in the reconciler loads non-superseded resolutions
-- into a temp table (_fte_active_resolutions ON COMMIT DROP) before Phase 1
-- classification begins. Downstream phases consume these decisions:
--   Phase 2  — observation classification override via observation_id join
--   Phase 5  — EXISTS(claim_id + action='confirm_payment_event') suppresses
--              'ambiguous' event status without erasing contradiction evidence
--   Phase 9  — counts rows as 'review_resolutions_applied' in return JSON
-- =============================================================================

begin;

-- =============================================================================
-- fte_review_resolutions — append-only typed reviewer decisions
-- =============================================================================
create table fte_review_resolutions (
  id                      uuid          primary key default gen_random_uuid(),

  -- ------------------------------------------------------------------
  -- Stable entity FKs — survive Phase 0 (IDs not regenerated by reconciler).
  -- ------------------------------------------------------------------
  practice_id             uuid          not null
                            references fte_practices(id) on delete restrict,
  claim_id                uuid
                            references fte_claims(id) on delete restrict,
  observation_id          uuid
                            references fte_observations(id) on delete restrict,
  evidence_id             uuid
                            references fte_evidence(id) on delete restrict,

  -- ------------------------------------------------------------------
  -- Typed reviewer decision — 15-value vocabulary across 3 categories.
  -- ------------------------------------------------------------------
  action                  text          not null
                            check (action in (
                              -- Observation-level (5)
                              'confirm_observation',
                              'reject_observation',
                              'mark_duplicate',
                              'resolve_contradiction',
                              'attach_corrected_value',
                              -- Payment / event-level (3)
                              'confirm_payment_event',
                              'reject_payment_event',
                              'assert_check_identity',
                              -- Position-level (7)
                              'confirm_short_pay',
                              'dismiss_short_pay',
                              'mark_position_resolved',
                              'mark_position_needs_correction',
                              'request_more_evidence',
                              'confirm_position_balanced',
                              'override_position_status'
                            )),

  -- ------------------------------------------------------------------
  -- Snapshot context — what was targeted at resolution time.
  -- ------------------------------------------------------------------
  target_type             text          not null
                            check (target_type in (
                              'observation', 'payment_event', 'position',
                              'review_entry', 'claim'
                            )),
  target_event_type       text,         -- e.g. 'payment_applied', 'denial_posted'
  target_review_reason    text,         -- e.g. 'late_retry_page_contradiction'
  target_claim_number     text,         -- readable claim identifier for auditability

  -- ------------------------------------------------------------------
  -- Volatile snapshot IDs — NO REFERENCES clause.
  -- Record derived-row IDs that existed when the resolution was created.
  -- Become stale after Phase 0 regenerates those rows — that is expected.
  -- ------------------------------------------------------------------
  source_review_queue_id  uuid,         -- snapshot of fte_review_queue.id
  source_claim_event_id   uuid,         -- snapshot of fte_claim_events.id
  source_position_id      uuid,         -- snapshot of fte_financial_positions.id

  -- ------------------------------------------------------------------
  -- Reviewer identity and decision details.
  -- ------------------------------------------------------------------
  resolved_by             text,         -- free-text; no FK (identity mgmt deferred)
  resolved_at             timestamptz   not null default now(),
  notes                   text,
  corrected_value         numeric(12,2),
  corrected_identifier    text,

  -- ------------------------------------------------------------------
  -- Supersession flag — the only mutable field after INSERT.
  -- Phase 0.5 filters WHERE is_superseded = false.
  -- ------------------------------------------------------------------
  is_superseded           boolean       not null default false,

  metadata                jsonb         not null default '{}'::jsonb
                            check (jsonb_typeof(metadata) = 'object'),
  created_at              timestamptz   not null default now(),
  updated_at              timestamptz   not null default now(),

  -- At least one stable or snapshot target beyond practice_id must be present.
  -- Prevents orphan resolutions with no traceable subject.
  constraint fte_review_resolutions_target_present
    check (
      claim_id              is not null
      or observation_id     is not null
      or evidence_id        is not null
      or source_review_queue_id is not null
      or source_claim_event_id  is not null
      or source_position_id     is not null
    )
);

comment on table fte_review_resolutions is
  'Append-only reviewer decisions that survive Phase 0''s DELETE of derived rows. '
  'Hard FKs point only to stable entity tables (fte_practices, fte_claims, '
  'fte_observations, fte_evidence) whose IDs are not regenerated by the reconciler. '
  'Volatile derived-row IDs (source_review_queue_id, source_claim_event_id, '
  'source_position_id) are snapshot fields with no REFERENCES clause; they may '
  'become stale after a reprocess — that is expected. Phase 0.5 loads non-superseded '
  'rows into _fte_active_resolutions (ON COMMIT DROP) before reconciliation begins.';

comment on column fte_review_resolutions.action is
  '15-value typed vocabulary: 5 observation-level (confirm/reject/duplicate/'
  'contradiction/corrected_value), 3 payment-level (confirm/reject/identity), '
  '7 position-level (short_pay/resolved/correction/evidence/balanced/override).';

comment on column fte_review_resolutions.source_review_queue_id is
  'Snapshot ONLY — no FK enforced. Records the fte_review_queue.id visible at '
  'resolution time. Becomes stale after Phase 0 regenerates derived rows.';
comment on column fte_review_resolutions.source_claim_event_id is
  'Snapshot ONLY — no FK enforced. Records the fte_claim_events.id visible at '
  'resolution time. Becomes stale after Phase 0 regenerates derived rows.';
comment on column fte_review_resolutions.source_position_id is
  'Snapshot ONLY — no FK enforced. Records the fte_financial_positions.id visible at '
  'resolution time. Becomes stale after Phase 0 regenerates derived rows.';

comment on column fte_review_resolutions.is_superseded is
  'Set true when a newer resolution replaces this one. The only column mutated '
  'after INSERT. Phase 0.5 loads only WHERE is_superseded = false. Prior rows '
  'are retained for audit — never deleted.';

comment on column fte_review_resolutions.resolved_by is
  'Free-text reviewer identifier. No FK to any users/auth table — reviewer '
  'identity management is deferred to a future task.';

comment on column fte_review_resolutions.corrected_value is
  'Numeric correction supplied by reviewer, e.g. the true paid amount when '
  'attach_corrected_value resolves an extraction error.';

comment on column fte_review_resolutions.corrected_identifier is
  'Text correction supplied by reviewer, e.g. the canonical check number when '
  'assert_check_identity resolves an OCR variant.';


-- =============================================================================
-- updated_at trigger — reuses function defined in migration 001.
-- =============================================================================
create trigger trg_fte_review_resolutions_updated_at
  before update on fte_review_resolutions
  for each row execute function fte_set_updated_at();


-- =============================================================================
-- Indexes
--   Primary access patterns:
--     Phase 0.5 — load all non-superseded resolutions for a practice (full scan)
--     Phase 5   — EXISTS check: claim_id + action = 'confirm_payment_event'
--     Phase 2   — observation classification override: observation_id + action
-- =============================================================================

-- Phase 0.5: load active (non-superseded) resolutions for a practice.
create index idx_fte_resolutions_practice_active
  on fte_review_resolutions (practice_id, is_superseded);

-- Phase 5: confirm_payment_event lookup by claim.
create index idx_fte_resolutions_claim_action
  on fte_review_resolutions (practice_id, claim_id, action);

-- Phase 2: observation classification override lookup.
create index idx_fte_resolutions_observation_action
  on fte_review_resolutions (practice_id, observation_id, action);

-- Audit/chronological scan by resolution date.
create index idx_fte_review_resolutions_resolved_at
  on fte_review_resolutions (practice_id, resolved_at desc);


-- =============================================================================
-- Row Level Security
--   Same deny-by-default stub pattern as all other tenant-scoped fte_ tables.
--   Supabase service_role (BYPASSRLS) is unaffected.
--   Wire fte_accessible_practice_ids() to a real membership lookup before
--   exposing this table to anon/authenticated traffic.
-- =============================================================================
alter table fte_review_resolutions enable row level security;

create policy fte_review_resolutions_rw on fte_review_resolutions
  for all
  using  (practice_id in (select fte_accessible_practice_ids()))
  with check (practice_id in (select fte_accessible_practice_ids()));


-- =============================================================================
-- End of migration 002.
-- =============================================================================

commit;
